export const GameEvents = {
  PLAYER_JOIN: 'playerJoin',
  USER_CONNECTED: 'userConnected',
  GAME_START: 'gameStart',
  GAME_STARTED: 'gameStarted',
  GAME_TIME_END: 'gameTimeEnd',
  GAME_FINISH: 'gameFinish',
  FIND_OPPONENT: 'findOpponent',
  OPPONENT_FOUND: 'opponentFound',
  WORD_SUBMIT: 'gameSubmit',
  WORD_SUBMIT_RESULT: 'wordSubmitResult',
  SET_NEXT_WORD: 'setNextWord',
  CONFIRM_GAME_RESULT: 'confirmGameResult',
  GAME_ERROR: 'gameError',
  STOP_FIND_OPPONENT: 'stopFindOpponent',
  EXIT_GAME: 'exitGame',
};
